export const subjects = [
  'Math',
  'Arts',
  'Science',
  'Physics',
  'Chemistry',
  'Music/Choir',
  'Life Skills',
  'Biology/Health',
  'Performing Arts',
  'Film/Photography',
  'Computer Sciences',
  'Drafting & Design',
  'Shop/Construction',
  'Business/Accounting',
  'Occupational Therapy',
  'History/Social Studies',
  'Language Arts/Literature',
  'Speech Therapy/New Languages',
  'Physical Education/Kinesiology',
  'Other',
];

export const levels = [
  'Grades 1-6',
  'Grades 7-9',
  'Grades 10-12+',
  'Upgrading',
  'Diploma',
  'Trades',
  'Undergraduate',
  'Masters',
  'Doctorate',
];

export const languages = [
  'Afrikaans',
  'Albanian',
  'Arabic',
  'Armenian',
  'Basque',
  'Bengali',
  'Bulgarian',
  'Catalan',
  'Cambodian',
  'Mandarin',
  'Croatian',
  'Czech',
  'Danish',
  'Dutch',
  'English',
  'Estonian',
  'Fiji',
  'Finnish',
  'French',
  'Georgian',
  'German',
  'Greek',
  'Gujarati',
  'Hebrew',
  'Hindi',
  'Hungarian',
  'Icelandic',
  'Indonesian',
  'Irish',
  'Italian',
  'Japanese',
  'Javanese',
  'Korean',
  'Latin',
  'Latvian',
  'Lithuanian',
  'Macedonian',
  'Malay',
  'Malayalam',
  'Maltese',
  'Maori',
  'Marathi',
  'Mongolian',
  'Nepali',
  'Norwegian',
  'Persian',
  'Polish',
  'Portuguese',
  'Punjabi',
  'Quechua',
  'Romanian',
  'Russian',
  'Samoan',
  'Serbian',
  'Slovak',
  'Slovenian',
  'Spanish',
  'Swahili',
  'Swedish',
  'Tamil',
  'Tatar',
  'Telugu',
  'Thai',
  'Tibetan',
  'Tonga',
  'Turkish',
  'Ukrainian',
  'Urdu',
  'Uzbek',
  'Vietnamese',
  'Welsh',
  'Xhosa',
];
