export default {
  HOSTNAME: process.env.NEXT_PUBLIC_HOSTNAME,
  GOOGLE_API_KEY: process.env.NEXT_PUBLIC_GOOGLE_API_KEY,
  MAIN_API_ENDPOINT: process.env.NEXT_PUBLIC_MAIN_API_ENDPOINT,
  NODE_ENV: process.env.NEXT_PUBLIC_NODE_ENV,
  RECAPTCHA_KEY: process.env.NEXT_PUBLIC_RECAPTCHA_KEY,
  WS_API_ENDPOINT: process.env.NEXT_PUBLIC_WS_API_ENDPOINT,
  GOOGLE_CLIENT_ID: process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID,
  FACEBOOK_APP_ID: process.env.NEXT_PUBLIC_FACEBOOK_APP_ID,
  LINKEDIN_CLIENT_ID: process.env.NEXT_PUBLIC_LINKEDIN_CLIENT_ID,
};
